name: Feature request
description: Something you would like the server to do.
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why does it matter?
